# GitHub Actions workflow
# https://help.github.com/actions

name: PR

on: [pull_request]

env:
  VERSION: ${{ github.event.pull_request.number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "yarn"

      # Install dependencies
      - run: yarn install

      # Analyze code for potential problems
      - run: yarn prettier --check .
      - run: yarn lint
      - run: yarn tsc --build

      # Test
      - run: yarn workspace api test
      - run: yarn workspace app test
      - run: yarn workspace edge test

      # Compile
      - run: yarn build

      # Deploy
      # - run: yarn deploy
